POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
  "name": "Product 3",
  "price": 300
}

###

GET http://localhost:8000/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODA5NzA0NzYsInN1YiI6ImQzMDIxNDk4LTA1MDctNGUwNi04ZjlkLTY1OGZjNzE1MjU3OCJ9.TBwnXtmP3z3BcmOcsqYJ_0XkJufcHO6miXoI4nE-sLw

###

GET http://localhost:8000/products/d069eb23-c7a5-4c87-ae70-455f687771e8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODA5NzA1NjUsInN1YiI6ImQzMDIxNDk4LTA1MDctNGUwNi04ZjlkLTY1OGZjNzE1MjU3OCJ9.vZ2Xl1JU9_eYvLr5iFwJMf-LnrX6BLMVks4Wo9QFlEk

###

PUT http://localhost:8000/products/d069eb23-c7a5-4c87-ae70-455f687771e8 HTTP/1.1
Content-Type: application/json

{
  "name": "Product 3",
  "price": 450
}

###

DELETE http://localhost:8000/products/d1f1314f-1937-4a47-b231-8d3d49dd7ce1 HTTP/1.1

###